### ISSUE TITLE
[Chore] azd provision and azd deploy errors

### ISSUE THREAD

**Issue by raj-microsoft** [Azure-Samples/contoso-real-estate#211]
- **azd provision** created all resources successfully but failed with restoring sql dumps  `failed running post hooks: 'postprovision' hook failed with exit code: '127', Path: 'C:\Users\xyz\AppData\Local\Temp\azd-postprovision-3989770095.sh'. : exit code: 127`

- **azd deploy** resulted on 'postpackage' hook failing with `Path: '..\..\infra\hooks\portal\predeploy.js'. : exit code: 2`

**Comment by anfibiacreativa** [comment]
Hi @raj-microsoft it looks like this issue is reproducible in your local environment (also windows?). Can you please add more information about the OS? 

The project is optimized to run on Codespaces. We welcome contributions to enhance it for cross-platform local development, but it's not something we will prioritize right now. Thank you!

**Comment by xpouyat** [comment]
@raj-microsoft For information  I got a similar issue with another project and fixed this error 127 by changing the end of line to LF (using VS Code, bottom bar) for the .sh file and the calling file.
