### ISSUE TITLE
[Chore](infra) Allow local IP to access PG

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/contoso-real-estate#374]
![image](https://github.com/Azure-Samples/contoso-real-estate/assets/41597107/889930b9-5ff3-4724-9dd1-3d0a8981be7d)

[17:22 of Pamela's video](https://www.youtube.com/watch?v=dqyHjUZSAuc)

**Comment by manekinekko** [comment]
Hi @diberry can you provide a description to what this issue is about (for future reference)?

FYI, we already support allowing single IP addresses here: 
https://github.com/Azure-Samples/contoso-real-estate/blob/e847420c77ca10a0bb514ea1573064e153ed1048/infra/core/database/postgresql/flexibleserver.bicep#L56-L62

To enable it, you need to set the correct flags here:
https://github.com/Azure-Samples/contoso-real-estate/blob/e847420c77ca10a0bb514ea1573064e153ed1048/infra/main.bicep#L294-L315
